version: '3.3'

services:
  postgres:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
